version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    
  api: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    command: npm run start
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
